[package]
name = "example-math-tools"
version = "0.1.0"
authors = ["Philipp Schloyer <Philipp.Schloyer@hs-augsburg.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"